server:
  enabled:
  server:
    persistentVolume:
      storageClass: null
      size: "25Gi"
  resources:
    server:
      limits:
        cpu: "3"
        memory: "5120Mi"
      requests:
        cpu: "1"
        memory: "5120Mi"

search-engine:
  enabled: true
  resources:
    data:
      limits:
        cpu: "1000m"
        memory: "8Gi"
      requests:
        cpu: "1000m"
        memory: "8Gi"
  persistence:
    data:
      persistentVolumeClaim:
        storageClassName: null
        size: "50Gi"
    backup:
      persistentVolumeClaim:
        size: "50Gi"
        storageClassName: null
    master:
      persistentVolumeClaim:
        storageClassName: null